### ISSUE TITLE
Gitea API not reachable

### ISSUE THREAD

**Issue by max-weis** [cwansart/ok-cli#4]
Wenn ich versuche eine Liste aller User zu bekommen, kriege ich folgenden Fehler: 
`net/url: invalid control character in URL`

https://github.com/cwansart/ok-cli/blob/372ac6584ca5f2ca869cf6eff8d344291cc71641/cmd/userlist.go#L19

**Comment by max-weis** [comment]
Fixed mit #2

**Comment by apollo7321** [comment]
Jup, du hattest versehentlich ein `\n` in die `cleanUrl` Funktion eingeschleußt. :D Hatte mich beim Test auch erst gewundert.
